### ISSUE TITLE
Reference this project from message-io

### ISSUE THREAD

**Issue by lemunozm** [ray33ee/Project-Midas#1]
Hi @ray33ee, 

I'm thinking to create a small list with some projects using *message-io* in its README. In case I finally do it, could I link this project? Thanks!

**Comment by ray33ee** [comment]
Absolutely! Please let me know when you do, it'll be interesting to see
what other projects use it!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lemunozm** [comment]
Done 😃  I put some projects there. The idea is to make this list grow. Thanks!!
